### ISSUE TITLE
CORS Error: Response to preflight request doesn't pass access control check

### ISSUE THREAD

**Issue by slee-aws** [aws-samples/aws-bedrock-with-rag-and-react#32]
Hello, after following the instructions in the README to run the python server and the react client, I am seeing several CORS errors in the browser javascript console. How can I resolve the CORS error?

Following are the errors that I see repeated in the console. The errors appear periodically without any interaction, and also when I attempt to upload a PDF using the FAISS dialog UI.
```javascript
Access to fetch at 'http://localhost:5000/api/check-vector' from origin 'http://localhost:3000'
has been blocked by CORS policy: Response to preflight request doesn't pass access control check:
No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response
serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by marshallbunch** [comment]
Hi @slee-aws -

I've found that CORS errors can be difficult to track down as it may indicate an issue other than CORS, but I'll do my best to help.
 
Can you tell me what browser you're using?

Are you running this on your local machine or Cloud9?

**Comment by marshallbunch** [comment]
Closing this issue as we haven't head back.
